# Java is not yet supported on Windows, define per os
language: minimal
    
before_install:
  # If on coverity_scan branch, allow only one job to continue. Choose a Linux one.
  - if [[ "${TRAVIS_BRANCH}" == "coverity_scan" && "${TRAVIS_JOB_NAME}" != "Linux JDK11 LTS" ]]; then exit 0; fi

# enable to get a stack trace on failed builds
# install:
#   - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -X

script:
  # Skip tests on coverity_scan branch
  - if [[ "${TRAVIS_BRANCH}" == "coverity_scan" ]]; then exit 0; fi
  - java -version
  - mvn test

after_success:
  # Only execute jacoco on one branch. Choose a Linux one.
  - bash <(curl -s https://codecov.io/bash)
  - if [ "${TRAVIS_JOB_NAME}" == "Linux JDK11 LTS" ]; then
      ./mvnw clean test jacoco:report coveralls:report;
      ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar;
    fi

addons:
  coverity_scan:
    project:
      name: "dblock/oshi"
      description: "Build submitted via Travis CI"
    notification_email: widdis@gmail.com
    build_command_prepend: "cov-configure --comptype gcc --compiler gcc-4.8 --template"
    build_command:   "./mvnw -DskipTests=true clean compile"
    branch_pattern: coverity_scan
  sonarcloud:
    organization: "default" # the key of the open source org
  hosts:
    - oshi
  hostname: oshi

# limit to 5 total builds and 2 builds on osx
jobs:
  include:
    - name: "Linux JDK11 LTS"
      os: linux
      language: java
      env: 
      # COVERITY_SCAN_TOKEN
      - secure: "JuTWT2u7BWQEJGMGkVvQMIQxwxajntxqbCGYt+bJD3JQhioPVFUJoEFrLCx+jJ0qLy5usrneCDFrvRhvTh6C+95kvHypvGQ3UoeWyXS8zD+GRPUyskbuQ7P60kqqIqc+naGd3uyGddniixoAA6C/Ptmknhls4FlhDCMjW3HDS0c="
      jdk: openjdk11      
    - name: "Linux JDK15 EA"
      os: linux
      language: java
      jdk: openjdk15
      dist: bionic
    - name: "Mac JDK8"
      os: osx
      language: java
      osx_image: xcode9.3
    - name: "Mac JDK14"
      os: osx

      language: java
      osx_image: xcode11.4
    - name: "Windows JDK 8"
      os: windows
      language: shell
      before_install:
        - export JDK="adopt@1.8.0-242"
        - travis_retry git clone --depth 1 https://github.com/DanySK/Gravis-CI.git $HOME/gravis
        - source $HOME/gravis/install-jdk
        - source $HOME/gravis/install-maven
# https://github.com/bndtools/bnd/issues/3903
  allow_failures:
    - name: "Linux JDK15 EA"
      os: linux
      jdk: openjdk15
      dist: bionic

